### ISSUE TITLE
Update text styles

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#14]
Want to tighten up text styles across the board. Updated styles below, will be smaller with tighter kerning and leading throughout. 

h1_header
font-family: Lato-Bold;
font-size: 40px;
color: #000000;
letter-spacing: .4px;
line-height: 55px;

h3_small caps
font-family: Lato-Bold;
font-size: 14px;
letter-spacing: 2px;
text-align: center;
line-height: 20px;

h4_body
font-family: Lato-Light;
font-size: 18px;
letter-spacing: 0.4px;
line-height: 28px;

h5_small body
font-family: Lato-Light;
font-size: 14px;
letter-spacing: 0.4px;
line-height: 22px;

work page log lines
font-family: Lato-Bold;
font-size: 30px;
letter-spacing: .4px;
line-height: 40px;

**Comment by kpettinga** [comment]
@portala when you mention "work page log lines" does that just mean the project titles on the work page?

**Comment by portala** [comment]
@kpettinga yes!

**Comment by portala** [comment]
@kpettinga i'm not seeing this change or a couple others from the list marked 'ready for review' (noted which ones in the comments) — i cleared history and checked in both chrome and safari. am i missing something?

**Comment by portala** [comment]
Still feeling big — a few updated styles below:

h1_header (this should be the same as the work page log lines now)
font-family: Lato-Bold;
font-size: 30px;
color: #000000;
letter-spacing: .4px;
line-height: 39px;

h2_logline
font-family: Lato-Light;
font-size: 25px;
color: #000000;
letter-spacing: 0.4px;
text-align: center;
line-height: 33px;

h3_small caps
font-family: Lato-Bold;
font-size: 12px;
letter-spacing: 2px;
text-align: center;
line-height: 20px;

**Comment by portala** [comment]
0822 Phase 2 Change

Lato Light = Aktiv Grotesk Light
Lato Bold = Aktiv Grotesk Bold
