### ISSUE TITLE
About_clean up team members

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#16]
Should have 25px space between each team member photo
Tighten leading between title and employee name

<img width="944" alt="screen shot 2018-06-04 at 6 27 36 pm" src="https://user-images.githubusercontent.com/37456166/40949935-4bbc7538-6825-11e8-9570-5a3013865baf.png">

**Comment by kpettinga** [comment]
@portala you only have about 10px between them in Zeplin. 10px seems to be the standard elsewhere as well (see culture page)

**Comment by portala** [comment]
10px is good, thank you!
