### ISSUE TITLE
Work_headline hover state

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#23]
Not loving the pulse here. Do you have a suggestion for something that might feel more "buttery"? 

<img width="675" alt="screen shot 2018-06-04 at 7 10 48 pm" src="https://user-images.githubusercontent.com/37456166/40951268-196e4876-682b-11e8-8975-59f284597079.png">

**Comment by kpettinga** [comment]
I do! stay tuned.

**Comment by kpettinga** [comment]
see #38
