### ISSUE TITLE
About_our story images

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#26]
Tried replacing images on the Our Story tab — 

<img width="863" alt="screen shot 2018-06-05 at 4 41 53 pm" src="https://user-images.githubusercontent.com/37456166/41008353-747a007a-68df-11e8-9caf-9e9edd7fd745.png">

___________

<img width="939" alt="screen shot 2018-06-05 at 4 43 57 pm" src="https://user-images.githubusercontent.com/37456166/41008513-327ffd18-68e0-11e8-837d-fff4a0f240e0.png">

**Comment by kpettinga** [comment]
@portala (Tess),

with the first set of the partners as kids, that weird cropping should be resolved now with some changes I've pushed up. **I will need to make sure, however, that those images are the same aspect ratios in order for them to match up in height.** 

with the second set of the partners as adults, you need to make sure that you have it set to "2 columns". It was set to "3" which was allowing space for a 3rd image that didn't exist.

**Comment by portala** [comment]
@kpettinga fixed! thank you
