### ISSUE TITLE
Home_headline

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#29]
<img width="223" alt="screen shot 2018-06-06 at 8 56 57 am" src="https://user-images.githubusercontent.com/37456166/41050224-991d7942-6967-11e8-81ff-b5f2aa8f515c.png">

Where can I adjust this in the staging site backend? Right now, it only works if I change the page title, not the excerpt (similar issue that we were having with work page)

**Comment by kpettinga** [comment]
Not sure why that wasn't working for you. I just tried it and it is working.
