### ISSUE TITLE
Home page_gallery height

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#32]
<img width="1376" alt="screen shot 2018-06-07 at 6 40 42 pm" src="https://user-images.githubusercontent.com/37456166/41135699-a7a0a89c-6a87-11e8-87a2-9d4588e47895.png">

I know the height of these elements is determined by the text — but is there a way to 'fake it' to make sure all the elements are the same height?

**Comment by kpettinga** [comment]
@portala (tess) do you mean you want the height of each _row_ to be the same? The images and text boxes in each row in your screenshot above look to be the same height.

**Comment by portala** [comment]
Yes sorry, each row the same height!

**Comment by portala** [comment]
@kpettinga can we also add 10px of space between the elements and each row?
