### ISSUE TITLE
Recognition_press rows

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#33]
<img width="999" alt="screen shot 2018-06-07 at 6 28 49 pm" src="https://user-images.githubusercontent.com/37456166/41135722-c9e4a836-6a87-11e8-9958-265e6449707b.png">
Possible to tighten up space between the two rows of press articles by 20px?

**Comment by kpettinga** [comment]
@portala (tess) the solution here is to just include all the press posts into one block. Currently you have them split into two separate blocks; thus, the large space. You can add as many press or award items to each block as you like and they will wrap based on the grid columns that you set.
