### ISSUE TITLE
Recognition_view all button

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#35]
<img width="1105" alt="screen shot 2018-06-07 at 7 28 08 pm" src="https://user-images.githubusercontent.com/37456166/41135992-f19053ac-6a88-11e8-8606-c323f5cd446a.png">
Is there a reason the 'view all' button isn't appearing? I marked multiple press items as 'Archived'.

**Comment by kpettinga** [comment]
@portala (tess) you need to use the "Recognition" page template.
