### ISSUE TITLE
Recognition_excerpt as block quote

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#45]
We'll want this headline to be a third party quote. Possible to use block quote formatting so we can attribute with a logo?

<img width="1007" alt="screen shot 2018-06-12 at 6 26 49 pm" src="https://user-images.githubusercontent.com/37456166/41325252-2e3aff9e-6e6e-11e8-8a88-fc6a11af168d.png">

**Comment by kpettinga** [comment]
@portala (tess) you can achieve this by putting quotes around the text in the Excerpt box and then just adding an image into the main content. Will provide example on the staging site.

**Comment by kpettinga** [comment]
See http://portala1984.staging.wpengine.com/press/
