### ISSUE TITLE
Blog_categories

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#46]
<img width="1123" alt="screen shot 2018-07-17 at 2 07 23 pm" src="https://user-images.githubusercontent.com/37456166/42845445-d205ca24-89ca-11e8-8f0a-2486c9ba4477.png">
Only 3 of the 6 categories I added in the backend are appearing.

**Comment by kpettinga** [comment]
Categories will only appear if you have posts assigned to them. Did you make sure the new categories you've created have some posts?
