### ISSUE TITLE
Navigation adjustments

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#58]
Let's bring down the height of the main navigation by ~7%. Ideally, it's a comfortable enough size that it doesn't have to shrink when you scroll down the page. 

Let's remove the twirl and shrink effect on the logo when scrolling.

<img width="1369" alt="screen shot 2018-10-05 at 10 41 20 am" src="https://user-images.githubusercontent.com/37456166/46550997-6d073b80-c88b-11e8-9248-b4a877253a96.png">

**Comment by kpettinga** [comment]
@portala fixed this. let me know how you like it.

**Comment by portala** [comment]
@kpettinga this is much better, thank you! Just need to make sure the color blocks are flush with the bottom of the navigation.

<img width="949" alt="screen shot 2018-10-08 at 10 16 49 am" src="https://user-images.githubusercontent.com/37456166/46623718-6410a700-cae3-11e8-8e6d-df7f1f41cbe2.png">
