### ISSUE TITLE
Image blocks

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#69]
Add space between images in these blocks to match Team tab (believe it's 10px). Should be across the board (ie, case study images also have a space)

<img width="874" alt="screen shot 2018-10-30 at 11 34 00 am" src="https://user-images.githubusercontent.com/37456166/47741531-bef77300-dc37-11e8-8771-58c277a2dce2.png">

**Comment by kpettinga** [comment]
Tess, I'm pretty sure I put this option in the custom fields. Will double check.

**Comment by kpettinga** [comment]
Ah ok nevermind, I only added the option to create gutters with the Tiles field. For the Image blocks field I just inserted gutters in the code.
