### ISSUE TITLE
Header images

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#71]
Remove built in color overlay on images, but keep color control of text (will either need to be black or white). We'll upload our own edited images. 

<img width="1326" alt="screen shot 2018-10-30 at 12 02 50 pm" src="https://user-images.githubusercontent.com/37456166/47743307-fd8f2c80-dc3b-11e8-9ab2-b8379cca7f8d.png">

<img width="305" alt="screen shot 2018-10-30 at 12 04 15 pm" src="https://user-images.githubusercontent.com/37456166/47743313-0253e080-dc3c-11e8-8ae4-be22feb30569.png">

**Comment by kpettinga** [comment]
🤔 

Tess, does this mean you don't want to control ANY background colors ? If you want to turn off the background color overlay, just delete the hex number from the field.

**Comment by portala** [comment]
Copy!
