### ISSUE TITLE
About_Culture

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#72]
Could we try making these rows full width to match the images on Team and Story? Keep space between rows / images.

<img width="1336" alt="screen shot 2018-10-30 at 12 09 01 pm" src="https://user-images.githubusercontent.com/37456166/47743753-02a0ab80-dc3d-11e8-8a85-36e875b1fe10.png">

**Comment by kpettinga** [comment]
Hey Tess, this is actually an option in the custom fields. Just make sure "contain grid to a max-width" is UN-checked.

![image](https://user-images.githubusercontent.com/1746410/48250636-42b31b80-e3ff-11e8-972b-d80c20965a2c.png)
